/*!   GeneXus C# 16_0_10-142546 on 4/20/2021 0:0:6.26
*/
gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.home', false, function () {
   this.ServerClass =  "wwpbaseobjects.home" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV5HomeSampleData=gx.fn.getControlValue("vHOMESAMPLEDATA") ;
      this.AV29SDTNotificationsData=gx.fn.getControlValue("vSDTNOTIFICATIONSDATA") ;
      this.AV29SDTNotificationsData=gx.fn.getControlValue("vSDTNOTIFICATIONSDATA") ;
   };
   this.e140b2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e150b2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,15,17,18,19,20,21,22,23,24,25,26,28,29,30,31,32,33,36,38,39,40,41,42,43,44,45,46,47,49,50,51,52,53,54,57,59,60,61,62,63,64,65,66,67,68,70,71,72,73,74,75,78,80,81,82,83,84,85,86,87,88,89,91,92,93,94,95,96,99,100,101,102,103,104,106,107,108,109,110,113,114,115,117,118,121,122,123,125,127,128,129];
   this.GXLastCtrlId =129;
   this.GridnotificationsContainer = new gx.grid.grid(this, 2,"WbpLvl2",105,"Gridnotifications","Gridnotifications","GridnotificationsContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.home",[],false,1,false,true,0,true,false,false,"CollWWPBaseObjects\SDTNotificationsData.SDTNotificationsDataItem",0,"px",0,"px","Nueva fila",true,false,false,null,null,false,"AV29SDTNotificationsData",false,[1,1,1,1],false,0,true,false);
   var GridnotificationsContainer = this.GridnotificationsContainer;
   GridnotificationsContainer.addSingleLineEdit("Notificationicon",106,"vNOTIFICATIONICON","","","NotificationIcon","svchar",0,"px",200,80,"left",null,[],"Notificationicon","NotificationIcon",true,0,false,false,"Attribute",1,"WWColumn");
   GridnotificationsContainer.addSingleLineEdit("GXV2",107,"SDTNOTIFICATIONSDATA__NOTIFICATIONICONCLASS","Notification Icon Class","","NotificationIconClass","svchar",0,"px",40,40,"left",null,[],"GXV2","GXV2",false,0,false,false,"Attribute",1,"WWColumn");
   GridnotificationsContainer.addSingleLineEdit("GXV3",108,"SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE","Notification Title","","NotificationTitle","svchar",0,"px",200,80,"left",null,[],"GXV3","GXV3",true,0,false,false,"Attribute",1,"WWColumn");
   GridnotificationsContainer.addSingleLineEdit("GXV4",109,"SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME","Notification Datetime","","NotificationDatetime","dtime",0,"px",14,14,"right",null,[],"GXV4","GXV4",true,5,false,false,"AttributeSecondary",1,"WWColumn");
   this.GridnotificationsContainer.emptyText = "";
   this.setGrid(GridnotificationsContainer);
   this.GridContainer = new gx.grid.grid(this, 3,"WbpLvl3",126,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.home",[],false,1,false,true,0,true,false,false,"CollWWPBaseObjects\HomeSampleData.HomeSampleDataItem",0,"px",0,"px","Nueva fila",true,false,false,null,null,false,"AV5HomeSampleData",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addSingleLineEdit("GXV6",127,"HOMESAMPLEDATA__PRODUCTNAME","Name","","ProductName","svchar",0,"px",40,40,"left",null,[],"GXV6","GXV6",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit("GXV7",128,"HOMESAMPLEDATA__PRODUCTPRICE","Price","","ProductPrice","decimal",0,"px",11,11,"right",null,[],"GXV7","GXV7",true,1,false,false,"Attribute",1,"WWColumn");
   GridContainer.addComboBox("GXV8",129,"HOMESAMPLEDATA__PRODUCTSTATUS","Status","ProductStatus","int",null,0,true,false,0,"px","");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.DVPANEL_TABLENOTIFICATIONSContainer = gx.uc.getNew(this, 97, 24, "BootstrapPanel", "DVPANEL_TABLENOTIFICATIONSContainer", "Dvpanel_tablenotifications", "DVPANEL_TABLENOTIFICATIONS");
   var DVPANEL_TABLENOTIFICATIONSContainer = this.DVPANEL_TABLENOTIFICATIONSContainer;
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Class", "Class", "", "char");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Cls", "Cls", "DVBootstrapResponsivePanel", "str");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Title", "Title", "Notificaciones", "str");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("IconPosition", "Iconposition", "Right", "str");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLENOTIFICATIONSContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   DVPANEL_TABLENOTIFICATIONSContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLENOTIFICATIONSContainer);
   this.UTCHARTCOLUMNLINEContainer = gx.uc.getNew(this, 116, 24, "QueryViewer", "UTCHARTCOLUMNLINEContainer", "Utchartcolumnline", "UTCHARTCOLUMNLINE");
   var UTCHARTCOLUMNLINEContainer = this.UTCHARTCOLUMNLINEContainer;
   UTCHARTCOLUMNLINEContainer.setProp("Enabled", "Enabled", true, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("ObjectId", "Objectid", "17", "str");
   UTCHARTCOLUMNLINEContainer.setProp("ObjectType", "Objecttype", "DataProvider", "str");
   UTCHARTCOLUMNLINEContainer.setProp("QueryInfo", "Queryinfo", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("ObjectInfo", "Objectinfo", "", "char");
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV16Axes', "vAXES", 'SetAxes');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV16Axes); });
   UTCHARTCOLUMNLINEContainer.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV17Parameters', "vPARAMETERS", 'SetParameters');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV17Parameters); });
   UTCHARTCOLUMNLINEContainer.setProp("ObjectName", "Objectname", "GetHomeSampleDataService", "str");
   UTCHARTCOLUMNLINEContainer.setProp("Object", "Objectcall", "", "str");
   UTCHARTCOLUMNLINEContainer.setProp("Class", "Class", "QueryViewer", "str");
   UTCHARTCOLUMNLINEContainer.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("AutoResize", "Autoresize", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("AutoResizeType", "Autoresizetype", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("Width", "Width", "100%", "str");
   UTCHARTCOLUMNLINEContainer.setProp("Height", "Height", "248", "str");
   UTCHARTCOLUMNLINEContainer.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("FontFamily", "Fontfamily", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("FontSize", "Fontsize", '', "int");
   UTCHARTCOLUMNLINEContainer.setProp("FontColor", "Fontcolor", '', "int");
   UTCHARTCOLUMNLINEContainer.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   UTCHARTCOLUMNLINEContainer.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("AllowSelection", "Allowselection", false, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("RememberLayout", "Rememberlayout", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("ExportToXML", "Exporttoxml", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("Type", "Type", "Chart", "str");
   UTCHARTCOLUMNLINEContainer.setProp("ShowDataAs", "Showdataas", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("Orientation", "Orientation", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("IncludeTrend", "Includetrend", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("TrendPeriod", "Trendperiod", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("ChartType", "Charttype", "ColumnLine", "str");
   UTCHARTCOLUMNLINEContainer.setProp("Title", "Title", "", "str");
   UTCHARTCOLUMNLINEContainer.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   UTCHARTCOLUMNLINEContainer.setProp("ShowValues", "Showvalues", true, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   UTCHARTCOLUMNLINEContainer.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "bool");
   UTCHARTCOLUMNLINEContainer.setProp("XAxisTitle", "Xaxistitle", "", "str");
   UTCHARTCOLUMNLINEContainer.setProp("YAxisTitle", "Yaxistitle", "", "str");
   UTCHARTCOLUMNLINEContainer.setProp("Paging", "Paging", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("PageSize", "Pagesize", '', "int");
   UTCHARTCOLUMNLINEContainer.setProp("CurrentPage", "Currentpage", '', "int");
   UTCHARTCOLUMNLINEContainer.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV18ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV18ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV18ItemClickData); });
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV19ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV19ItemDoubleClickData); });
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV20DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV20DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV20DragAndDropData); });
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV21FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV21FilterChangedData); });
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV22ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV22ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV22ItemExpandData); });
   UTCHARTCOLUMNLINEContainer.addV2CFunction('AV23ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   UTCHARTCOLUMNLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV23ItemCollapseData); });
   UTCHARTCOLUMNLINEContainer.setProp("AppSettings", "Appsettings", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("ExecuteShow", "Executeshow", false, "boolean");
   UTCHARTCOLUMNLINEContainer.setProp("ServiceUrl", "Serviceurl", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("GenType", "Gentype", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   UTCHARTCOLUMNLINEContainer.setProp("Visible", "Visible", true, "bool");
   UTCHARTCOLUMNLINEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(UTCHARTCOLUMNLINEContainer);
   this.DVPANEL_TABLECHART1Container = gx.uc.getNew(this, 111, 24, "BootstrapPanel", "DVPANEL_TABLECHART1Container", "Dvpanel_tablechart1", "DVPANEL_TABLECHART1");
   var DVPANEL_TABLECHART1Container = this.DVPANEL_TABLECHART1Container;
   DVPANEL_TABLECHART1Container.setProp("Class", "Class", "", "char");
   DVPANEL_TABLECHART1Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLECHART1Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLECHART1Container.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLECHART1Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLECHART1Container.setProp("Cls", "Cls", "DVBootstrapResponsivePanel", "str");
   DVPANEL_TABLECHART1Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLECHART1Container.setProp("Title", "Title", "Sales Table", "str");
   DVPANEL_TABLECHART1Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("IconPosition", "Iconposition", "Right", "str");
   DVPANEL_TABLECHART1Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLECHART1Container.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   DVPANEL_TABLECHART1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLECHART1Container);
   this.UTCHARTSMOOTHLINEContainer = gx.uc.getNew(this, 124, 24, "QueryViewer", "UTCHARTSMOOTHLINEContainer", "Utchartsmoothline", "UTCHARTSMOOTHLINE");
   var UTCHARTSMOOTHLINEContainer = this.UTCHARTSMOOTHLINEContainer;
   UTCHARTSMOOTHLINEContainer.setProp("Enabled", "Enabled", true, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ObjectId", "Objectid", "17", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ObjectType", "Objecttype", "DataProvider", "str");
   UTCHARTSMOOTHLINEContainer.setProp("QueryInfo", "Queryinfo", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("ObjectInfo", "Objectinfo", "", "char");
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV16Axes', "vAXES", 'SetAxes');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV16Axes); });
   UTCHARTSMOOTHLINEContainer.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV17Parameters', "vPARAMETERS", 'SetParameters');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV17Parameters); });
   UTCHARTSMOOTHLINEContainer.setProp("ObjectName", "Objectname", "GetHomeSampleDataService", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Object", "Objectcall", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Class", "Class", "QueryViewer", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("AutoResize", "Autoresize", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("AutoResizeType", "Autoresizetype", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("Width", "Width", "100%", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Height", "Height", "450", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("FontFamily", "Fontfamily", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("FontSize", "Fontsize", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("FontColor", "Fontcolor", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("AllowSelection", "Allowselection", false, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("RememberLayout", "Rememberlayout", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToXML", "Exporttoxml", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("Type", "Type", "Chart", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ShowDataAs", "Showdataas", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("Orientation", "Orientation", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("IncludeTrend", "Includetrend", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("TrendPeriod", "Trendperiod", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ChartType", "Charttype", "SmoothLine", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Title", "Title", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ShowValues", "Showvalues", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   UTCHARTSMOOTHLINEContainer.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("XAxisTitle", "Xaxistitle", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("YAxisTitle", "Yaxistitle", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Paging", "Paging", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("PageSize", "Pagesize", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("CurrentPage", "Currentpage", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV18ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV18ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV18ItemClickData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV19ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV19ItemDoubleClickData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV20DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV20DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV20DragAndDropData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV21FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV21FilterChangedData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV22ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV22ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV22ItemExpandData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV23ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV23ItemCollapseData); });
   UTCHARTSMOOTHLINEContainer.setProp("AppSettings", "Appsettings", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ExecuteShow", "Executeshow", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ServiceUrl", "Serviceurl", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("GenType", "Gentype", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("Visible", "Visible", true, "bool");
   UTCHARTSMOOTHLINEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(UTCHARTSMOOTHLINEContainer);
   this.DVPANEL_TABLECHART2Container = gx.uc.getNew(this, 119, 24, "BootstrapPanel", "DVPANEL_TABLECHART2Container", "Dvpanel_tablechart2", "DVPANEL_TABLECHART2");
   var DVPANEL_TABLECHART2Container = this.DVPANEL_TABLECHART2Container;
   DVPANEL_TABLECHART2Container.setProp("Class", "Class", "", "char");
   DVPANEL_TABLECHART2Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLECHART2Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLECHART2Container.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLECHART2Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLECHART2Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLECHART2Container.setProp("Cls", "Cls", "DVBootstrapResponsivePanel", "str");
   DVPANEL_TABLECHART2Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLECHART2Container.setProp("Title", "Title", "Task Board", "str");
   DVPANEL_TABLECHART2Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_TABLECHART2Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLECHART2Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLECHART2Container.setProp("IconPosition", "Iconposition", "Right", "str");
   DVPANEL_TABLECHART2Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLECHART2Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLECHART2Container.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   DVPANEL_TABLECHART2Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLECHART2Container);
   this.PROGRESSCARD4Container = gx.uc.getNew(this, 90, 24, "DVProgressIndicator", "PROGRESSCARD4Container", "Progresscard4", "PROGRESSCARD4");
   var PROGRESSCARD4Container = this.PROGRESSCARD4Container;
   PROGRESSCARD4Container.setProp("Class", "Class", "", "char");
   PROGRESSCARD4Container.setProp("Enabled", "Enabled", true, "boolean");
   PROGRESSCARD4Container.setProp("Type", "Type", "Bar", "str");
   PROGRESSCARD4Container.setProp("CircleCaptionType", "Circlecaptiontype", "", "char");
   PROGRESSCARD4Container.setProp("Caption", "Caption", "", "str");
   PROGRESSCARD4Container.setProp("Subtitle", "Subtitle", "", "char");
   PROGRESSCARD4Container.setProp("RawHTML", "Rawhtml", "", "char");
   PROGRESSCARD4Container.setProp("Cls", "Cls", "ProgressBarAdminCard", "str");
   PROGRESSCARD4Container.setProp("Percentage", "Percentage", 40, "num");
   PROGRESSCARD4Container.setProp("BarWidth", "Barwidth", "100%", "str");
   PROGRESSCARD4Container.setProp("CircleWidth", "Circlewidth", '', "int");
   PROGRESSCARD4Container.setProp("CircleProgressWidth", "Circleprogresswidth", '', "int");
   PROGRESSCARD4Container.setProp("AnimateOnStart", "Animateonstart", true, "bool");
   PROGRESSCARD4Container.setProp("Visible", "Visible", true, "bool");
   PROGRESSCARD4Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(PROGRESSCARD4Container);
   this.PROGRESSCARD3Container = gx.uc.getNew(this, 69, 24, "DVProgressIndicator", "PROGRESSCARD3Container", "Progresscard3", "PROGRESSCARD3");
   var PROGRESSCARD3Container = this.PROGRESSCARD3Container;
   PROGRESSCARD3Container.setProp("Class", "Class", "", "char");
   PROGRESSCARD3Container.setProp("Enabled", "Enabled", true, "boolean");
   PROGRESSCARD3Container.setProp("Type", "Type", "Bar", "str");
   PROGRESSCARD3Container.setProp("CircleCaptionType", "Circlecaptiontype", "", "char");
   PROGRESSCARD3Container.setProp("Caption", "Caption", "", "str");
   PROGRESSCARD3Container.setProp("Subtitle", "Subtitle", "", "char");
   PROGRESSCARD3Container.setProp("RawHTML", "Rawhtml", "", "char");
   PROGRESSCARD3Container.setProp("Cls", "Cls", "ProgressBarAdminCard", "str");
   PROGRESSCARD3Container.setProp("Percentage", "Percentage", 70, "num");
   PROGRESSCARD3Container.setProp("BarWidth", "Barwidth", "100%", "str");
   PROGRESSCARD3Container.setProp("CircleWidth", "Circlewidth", '', "int");
   PROGRESSCARD3Container.setProp("CircleProgressWidth", "Circleprogresswidth", '', "int");
   PROGRESSCARD3Container.setProp("AnimateOnStart", "Animateonstart", true, "bool");
   PROGRESSCARD3Container.setProp("Visible", "Visible", true, "bool");
   PROGRESSCARD3Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(PROGRESSCARD3Container);
   this.PROGRESSCARD2Container = gx.uc.getNew(this, 48, 24, "DVProgressIndicator", "PROGRESSCARD2Container", "Progresscard2", "PROGRESSCARD2");
   var PROGRESSCARD2Container = this.PROGRESSCARD2Container;
   PROGRESSCARD2Container.setProp("Class", "Class", "", "char");
   PROGRESSCARD2Container.setProp("Enabled", "Enabled", true, "boolean");
   PROGRESSCARD2Container.setProp("Type", "Type", "Bar", "str");
   PROGRESSCARD2Container.setProp("CircleCaptionType", "Circlecaptiontype", "", "char");
   PROGRESSCARD2Container.setProp("Caption", "Caption", "", "str");
   PROGRESSCARD2Container.setProp("Subtitle", "Subtitle", "", "char");
   PROGRESSCARD2Container.setProp("RawHTML", "Rawhtml", "", "char");
   PROGRESSCARD2Container.setProp("Cls", "Cls", "ProgressBarAdminCard", "str");
   PROGRESSCARD2Container.setProp("Percentage", "Percentage", 20, "num");
   PROGRESSCARD2Container.setProp("BarWidth", "Barwidth", "100%", "str");
   PROGRESSCARD2Container.setProp("CircleWidth", "Circlewidth", '', "int");
   PROGRESSCARD2Container.setProp("CircleProgressWidth", "Circleprogresswidth", '', "int");
   PROGRESSCARD2Container.setProp("AnimateOnStart", "Animateonstart", true, "bool");
   PROGRESSCARD2Container.setProp("Visible", "Visible", true, "bool");
   PROGRESSCARD2Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(PROGRESSCARD2Container);
   this.PROGRESSCARD1Container = gx.uc.getNew(this, 27, 24, "DVProgressIndicator", "PROGRESSCARD1Container", "Progresscard1", "PROGRESSCARD1");
   var PROGRESSCARD1Container = this.PROGRESSCARD1Container;
   PROGRESSCARD1Container.setProp("Class", "Class", "", "char");
   PROGRESSCARD1Container.setProp("Enabled", "Enabled", true, "boolean");
   PROGRESSCARD1Container.setProp("Type", "Type", "Bar", "str");
   PROGRESSCARD1Container.setProp("CircleCaptionType", "Circlecaptiontype", "", "char");
   PROGRESSCARD1Container.setProp("Caption", "Caption", "", "str");
   PROGRESSCARD1Container.setProp("Subtitle", "Subtitle", "", "char");
   PROGRESSCARD1Container.setProp("RawHTML", "Rawhtml", "", "char");
   PROGRESSCARD1Container.setProp("Cls", "Cls", "ProgressBarAdminCard", "str");
   PROGRESSCARD1Container.setProp("Percentage", "Percentage", 50, "num");
   PROGRESSCARD1Container.setProp("BarWidth", "Barwidth", "100%", "str");
   PROGRESSCARD1Container.setProp("CircleWidth", "Circlewidth", '', "int");
   PROGRESSCARD1Container.setProp("CircleProgressWidth", "Circleprogresswidth", '', "int");
   PROGRESSCARD1Container.setProp("AnimateOnStart", "Animateonstart", true, "bool");
   PROGRESSCARD1Container.setProp("Visible", "Visible", true, "bool");
   PROGRESSCARD1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(PROGRESSCARD1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"TABLECARDS",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[12]={ id: 12, fld:"CARD1",grid:0};
   GXValidFnc[15]={ id: 15, fld:"PROGRESSCARD1ICON", format:2,grid:0};
   GXValidFnc[17]={ id: 17, fld:"TABLECARD1INFO",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"DESCRIPTIONCARD1", format:0,grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id:24 ,lvl:0,type:"int",len:8,dec:0,sign:false,pic:"ZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD1",gxz:"ZV13ValueCard1",gxold:"OV13ValueCard1",gxvar:"AV13ValueCard1",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV13ValueCard1=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV13ValueCard1=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vVALUECARD1",gx.O.AV13ValueCard1,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV13ValueCard1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vVALUECARD1",'.')},nac:gx.falseFn};
   this.declareDomainHdlr( 24 , function() {
   });
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id: 26, fld:"",grid:0};
   GXValidFnc[28]={ id: 28, fld:"",grid:0};
   GXValidFnc[29]={ id: 29, fld:"",grid:0};
   GXValidFnc[30]={ id: 30, fld:"",grid:0};
   GXValidFnc[31]={ id:31 ,lvl:0,type:"svchar",len:400,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vADDITIONALDATACARD1",gxz:"ZV14AdditionalDataCard1",gxold:"OV14AdditionalDataCard1",gxvar:"AV14AdditionalDataCard1",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14AdditionalDataCard1=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14AdditionalDataCard1=Value},v2c:function(){gx.fn.setControlValue("vADDITIONALDATACARD1",gx.O.AV14AdditionalDataCard1,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14AdditionalDataCard1=this.val()},val:function(){return gx.fn.getControlValue("vADDITIONALDATACARD1")},nac:gx.falseFn};
   GXValidFnc[32]={ id: 32, fld:"",grid:0};
   GXValidFnc[33]={ id: 33, fld:"CARD2",grid:0};
   GXValidFnc[36]={ id: 36, fld:"PROGRESSCARD2ICON", format:2,grid:0};
   GXValidFnc[38]={ id: 38, fld:"TABLECARD2INFO",grid:0};
   GXValidFnc[39]={ id: 39, fld:"",grid:0};
   GXValidFnc[40]={ id: 40, fld:"",grid:0};
   GXValidFnc[41]={ id: 41, fld:"DESCRIPTIONCARD2", format:0,grid:0};
   GXValidFnc[42]={ id: 42, fld:"",grid:0};
   GXValidFnc[43]={ id: 43, fld:"",grid:0};
   GXValidFnc[44]={ id: 44, fld:"",grid:0};
   GXValidFnc[45]={ id:45 ,lvl:0,type:"int",len:8,dec:0,sign:false,pic:"$ZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD2",gxz:"ZV11ValueCard2",gxold:"OV11ValueCard2",gxvar:"AV11ValueCard2",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11ValueCard2=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11ValueCard2=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vVALUECARD2",gx.O.AV11ValueCard2,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV11ValueCard2=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vVALUECARD2",'.')},nac:gx.falseFn};
   this.declareDomainHdlr( 45 , function() {
   });
   GXValidFnc[46]={ id: 46, fld:"",grid:0};
   GXValidFnc[47]={ id: 47, fld:"",grid:0};
   GXValidFnc[49]={ id: 49, fld:"",grid:0};
   GXValidFnc[50]={ id: 50, fld:"",grid:0};
   GXValidFnc[51]={ id: 51, fld:"",grid:0};
   GXValidFnc[52]={ id:52 ,lvl:0,type:"svchar",len:400,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vADDITIONALDATACARD2",gxz:"ZV12AdditionalDataCard2",gxold:"OV12AdditionalDataCard2",gxvar:"AV12AdditionalDataCard2",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12AdditionalDataCard2=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV12AdditionalDataCard2=Value},v2c:function(){gx.fn.setControlValue("vADDITIONALDATACARD2",gx.O.AV12AdditionalDataCard2,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV12AdditionalDataCard2=this.val()},val:function(){return gx.fn.getControlValue("vADDITIONALDATACARD2")},nac:gx.falseFn};
   GXValidFnc[53]={ id: 53, fld:"",grid:0};
   GXValidFnc[54]={ id: 54, fld:"CARD3",grid:0};
   GXValidFnc[57]={ id: 57, fld:"PROGRESSCARD3ICON", format:2,grid:0};
   GXValidFnc[59]={ id: 59, fld:"TABLECARD3INFO",grid:0};
   GXValidFnc[60]={ id: 60, fld:"",grid:0};
   GXValidFnc[61]={ id: 61, fld:"",grid:0};
   GXValidFnc[62]={ id: 62, fld:"DESCRIPTIONCARD3", format:0,grid:0};
   GXValidFnc[63]={ id: 63, fld:"",grid:0};
   GXValidFnc[64]={ id: 64, fld:"",grid:0};
   GXValidFnc[65]={ id: 65, fld:"",grid:0};
   GXValidFnc[66]={ id:66 ,lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD3",gxz:"ZV9ValueCard3",gxold:"OV9ValueCard3",gxvar:"AV9ValueCard3",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV9ValueCard3=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV9ValueCard3=Value},v2c:function(){gx.fn.setControlValue("vVALUECARD3",gx.O.AV9ValueCard3,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV9ValueCard3=this.val()},val:function(){return gx.fn.getControlValue("vVALUECARD3")},nac:gx.falseFn};
   this.declareDomainHdlr( 66 , function() {
   });
   GXValidFnc[67]={ id: 67, fld:"",grid:0};
   GXValidFnc[68]={ id: 68, fld:"",grid:0};
   GXValidFnc[70]={ id: 70, fld:"",grid:0};
   GXValidFnc[71]={ id: 71, fld:"",grid:0};
   GXValidFnc[72]={ id: 72, fld:"",grid:0};
   GXValidFnc[73]={ id:73 ,lvl:0,type:"svchar",len:400,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vADDITIONALDATACARD3",gxz:"ZV10AdditionalDataCard3",gxold:"OV10AdditionalDataCard3",gxvar:"AV10AdditionalDataCard3",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV10AdditionalDataCard3=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV10AdditionalDataCard3=Value},v2c:function(){gx.fn.setControlValue("vADDITIONALDATACARD3",gx.O.AV10AdditionalDataCard3,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV10AdditionalDataCard3=this.val()},val:function(){return gx.fn.getControlValue("vADDITIONALDATACARD3")},nac:gx.falseFn};
   GXValidFnc[74]={ id: 74, fld:"",grid:0};
   GXValidFnc[75]={ id: 75, fld:"CARD4",grid:0};
   GXValidFnc[78]={ id: 78, fld:"PROGRESSCARD4ICON", format:2,grid:0};
   GXValidFnc[80]={ id: 80, fld:"TABLECARD4INFO",grid:0};
   GXValidFnc[81]={ id: 81, fld:"",grid:0};
   GXValidFnc[82]={ id: 82, fld:"",grid:0};
   GXValidFnc[83]={ id: 83, fld:"DESCRIPTIONCARD4", format:0,grid:0};
   GXValidFnc[84]={ id: 84, fld:"",grid:0};
   GXValidFnc[85]={ id: 85, fld:"",grid:0};
   GXValidFnc[86]={ id: 86, fld:"",grid:0};
   GXValidFnc[87]={ id:87 ,lvl:0,type:"int",len:8,dec:0,sign:false,pic:"ZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD4",gxz:"ZV7ValueCard4",gxold:"OV7ValueCard4",gxvar:"AV7ValueCard4",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV7ValueCard4=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV7ValueCard4=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vVALUECARD4",gx.O.AV7ValueCard4,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV7ValueCard4=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vVALUECARD4",'.')},nac:gx.falseFn};
   this.declareDomainHdlr( 87 , function() {
   });
   GXValidFnc[88]={ id: 88, fld:"",grid:0};
   GXValidFnc[89]={ id: 89, fld:"",grid:0};
   GXValidFnc[91]={ id: 91, fld:"",grid:0};
   GXValidFnc[92]={ id: 92, fld:"",grid:0};
   GXValidFnc[93]={ id: 93, fld:"",grid:0};
   GXValidFnc[94]={ id:94 ,lvl:0,type:"svchar",len:400,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vADDITIONALDATACARD4",gxz:"ZV8AdditionalDataCard4",gxold:"OV8AdditionalDataCard4",gxvar:"AV8AdditionalDataCard4",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV8AdditionalDataCard4=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV8AdditionalDataCard4=Value},v2c:function(){gx.fn.setControlValue("vADDITIONALDATACARD4",gx.O.AV8AdditionalDataCard4,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV8AdditionalDataCard4=this.val()},val:function(){return gx.fn.getControlValue("vADDITIONALDATACARD4")},nac:gx.falseFn};
   GXValidFnc[95]={ id: 95, fld:"",grid:0};
   GXValidFnc[96]={ id: 96, fld:"",grid:0};
   GXValidFnc[99]={ id: 99, fld:"TABLENOTIFICATIONS",grid:0};
   GXValidFnc[100]={ id: 100, fld:"",grid:0};
   GXValidFnc[101]={ id: 101, fld:"",grid:0};
   GXValidFnc[102]={ id: 102, fld:"NOTIFICATIONSSUBTITLE", format:0,grid:0};
   GXValidFnc[103]={ id: 103, fld:"",grid:0};
   GXValidFnc[104]={ id: 104, fld:"",grid:0};
   GXValidFnc[106]={ id:106 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:1,isacc:0,grid:105,gxgrid:this.GridnotificationsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vNOTIFICATIONICON",gxz:"ZV28NotificationIcon",gxold:"OV28NotificationIcon",gxvar:"AV28NotificationIcon",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV28NotificationIcon=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV28NotificationIcon=Value},v2c:function(row){gx.fn.setGridControlValue("vNOTIFICATIONICON",row || gx.fn.currentGridRowImpl(105),gx.O.AV28NotificationIcon,1)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV28NotificationIcon=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vNOTIFICATIONICON",row || gx.fn.currentGridRowImpl(105))},nac:gx.falseFn};
   GXValidFnc[107]={ id:107 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:105,gxgrid:this.GridnotificationsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONICONCLASS",gxz:"ZV33GXV2",gxold:"OV33GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV2=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV33GXV2=Value},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONICONCLASS",row || gx.fn.currentGridRowImpl(105),gx.O.GXV2,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV2=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONICONCLASS",row || gx.fn.currentGridRowImpl(105))},nac:gx.falseFn};
   GXValidFnc[108]={ id:108 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:1,isacc:0,grid:105,gxgrid:this.GridnotificationsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE",gxz:"ZV34GXV3",gxold:"OV34GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV3=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV34GXV3=Value},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE",row || gx.fn.currentGridRowImpl(105),gx.O.GXV3,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV3=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONTITLE",row || gx.fn.currentGridRowImpl(105))},nac:gx.falseFn};
   GXValidFnc[109]={ id:109 ,lvl:2,type:"dtime",len:8,dec:5,sign:false,ro:1,isacc:0,grid:105,gxgrid:this.GridnotificationsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME",gxz:"ZV35GXV4",gxold:"OV35GXV4",gxvar:"GXV4",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/99 99:99",dec:5},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV4=gx.fn.toDatetimeValue(Value,"Y4MD")},v2z:function(Value){if(Value!==undefined)gx.O.ZV35GXV4=gx.fn.toDatetimeValue(Value)},v2c:function(row){gx.fn.setGridControlValue("SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME",row || gx.fn.currentGridRowImpl(105),gx.O.GXV4,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV4=gx.fn.toDatetimeValue(this.val(row))},val:function(row){return gx.fn.getGridDateTimeValue("SDTNOTIFICATIONSDATA__NOTIFICATIONDATETIME",row || gx.fn.currentGridRowImpl(105))},nac:gx.falseFn};
   GXValidFnc[110]={ id: 110, fld:"",grid:0};
   GXValidFnc[113]={ id: 113, fld:"TABLECHART1",grid:0};
   GXValidFnc[114]={ id: 114, fld:"",grid:0};
   GXValidFnc[115]={ id: 115, fld:"",grid:0};
   GXValidFnc[117]={ id: 117, fld:"",grid:0};
   GXValidFnc[118]={ id: 118, fld:"",grid:0};
   GXValidFnc[121]={ id: 121, fld:"TABLECHART2",grid:0};
   GXValidFnc[122]={ id: 122, fld:"",grid:0};
   GXValidFnc[123]={ id: 123, fld:"",grid:0};
   GXValidFnc[125]={ id: 125, fld:"",grid:0};
   GXValidFnc[127]={ id:127 ,lvl:3,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:126,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"HOMESAMPLEDATA__PRODUCTNAME",gxz:"ZV37GXV6",gxold:"OV37GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV6=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV37GXV6=Value},v2c:function(row){gx.fn.setGridControlValue("HOMESAMPLEDATA__PRODUCTNAME",row || gx.fn.currentGridRowImpl(126),gx.O.GXV6,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV6=this.val(row)},val:function(row){return gx.fn.getGridControlValue("HOMESAMPLEDATA__PRODUCTNAME",row || gx.fn.currentGridRowImpl(126))},nac:gx.falseFn};
   GXValidFnc[128]={ id:128 ,lvl:3,type:"decimal",len:8,dec:1,sign:false,pic:"$ ZZZ,ZZ9.9",ro:1,isacc:0,grid:126,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"HOMESAMPLEDATA__PRODUCTPRICE",gxz:"ZV38GXV7",gxold:"OV38GXV7",gxvar:"GXV7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV7=gx.fn.toDecimalValue(Value,',','.')},v2z:function(Value){if(Value!==undefined)gx.O.ZV38GXV7=gx.fn.toDecimalValue(Value,'.',',')},v2c:function(row){gx.fn.setGridDecimalValue("HOMESAMPLEDATA__PRODUCTPRICE",row || gx.fn.currentGridRowImpl(126),gx.O.GXV7,1,',')},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV7=this.val(row)},val:function(row){return gx.fn.getGridDecimalValue("HOMESAMPLEDATA__PRODUCTPRICE",row || gx.fn.currentGridRowImpl(126),'.',',')},nac:gx.falseFn};
   GXValidFnc[129]={ id:129 ,lvl:3,type:"int",len:1,dec:0,sign:false,pic:"9",ro:1,isacc:0,grid:126,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"HOMESAMPLEDATA__PRODUCTSTATUS",gxz:"ZV39GXV8",gxold:"OV39GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.GXV8=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV39GXV8=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridComboBoxValue("HOMESAMPLEDATA__PRODUCTSTATUS",row || gx.fn.currentGridRowImpl(126),gx.O.GXV8)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV8=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("HOMESAMPLEDATA__PRODUCTSTATUS",row || gx.fn.currentGridRowImpl(126),'.')},nac:gx.falseFn};
   this.AV13ValueCard1 = 0 ;
   this.ZV13ValueCard1 = 0 ;
   this.OV13ValueCard1 = 0 ;
   this.AV14AdditionalDataCard1 = "" ;
   this.ZV14AdditionalDataCard1 = "" ;
   this.OV14AdditionalDataCard1 = "" ;
   this.AV11ValueCard2 = 0 ;
   this.ZV11ValueCard2 = 0 ;
   this.OV11ValueCard2 = 0 ;
   this.AV12AdditionalDataCard2 = "" ;
   this.ZV12AdditionalDataCard2 = "" ;
   this.OV12AdditionalDataCard2 = "" ;
   this.AV9ValueCard3 = "" ;
   this.ZV9ValueCard3 = "" ;
   this.OV9ValueCard3 = "" ;
   this.AV10AdditionalDataCard3 = "" ;
   this.ZV10AdditionalDataCard3 = "" ;
   this.OV10AdditionalDataCard3 = "" ;
   this.AV7ValueCard4 = 0 ;
   this.ZV7ValueCard4 = 0 ;
   this.OV7ValueCard4 = 0 ;
   this.AV8AdditionalDataCard4 = "" ;
   this.ZV8AdditionalDataCard4 = "" ;
   this.OV8AdditionalDataCard4 = "" ;
   this.ZV28NotificationIcon = "" ;
   this.OV28NotificationIcon = "" ;
   this.ZV33GXV2 = "" ;
   this.OV33GXV2 = "" ;
   this.ZV34GXV3 = "" ;
   this.OV34GXV3 = "" ;
   this.ZV35GXV4 = gx.date.nullDate() ;
   this.OV35GXV4 = gx.date.nullDate() ;
   this.ZV37GXV6 = "" ;
   this.OV37GXV6 = "" ;
   this.ZV38GXV7 = 0 ;
   this.OV38GXV7 = 0 ;
   this.ZV39GXV8 = 0 ;
   this.OV39GXV8 = 0 ;
   this.AV13ValueCard1 = 0 ;
   this.AV14AdditionalDataCard1 = "" ;
   this.AV11ValueCard2 = 0 ;
   this.AV12AdditionalDataCard2 = "" ;
   this.AV9ValueCard3 = "" ;
   this.AV10AdditionalDataCard3 = "" ;
   this.AV7ValueCard4 = 0 ;
   this.AV8AdditionalDataCard4 = "" ;
   this.AV16Axes = [ ] ;
   this.AV28NotificationIcon = "" ;
   this.GXV2 = "" ;
   this.GXV3 = "" ;
   this.GXV4 = gx.date.nullDate() ;
   this.GXV6 = "" ;
   this.GXV7 = 0 ;
   this.GXV8 = 0 ;
   this.AV5HomeSampleData = [ ] ;
   this.AV29SDTNotificationsData = [ ] ;
   this.Events = {"e140b2_client": ["ENTER", true] ,"e150b2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'GRIDNOTIFICATIONS_nEOF'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["START"] = [[{av:'AV16Axes',fld:'vAXES',pic:''},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'GRIDNOTIFICATIONS_nEOF'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[{av:'gx.fn.getCtrlProperty("TABLECHART2","Height")',ctrl:'TABLECHART2',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'AV13ValueCard1',fld:'vVALUECARD1',pic:'ZZ,ZZZ,ZZ9'},{av:'AV11ValueCard2',fld:'vVALUECARD2',pic:'$ZZ,ZZZ,ZZ9'},{av:'AV9ValueCard3',fld:'vVALUECARD3',pic:''},{av:'AV7ValueCard4',fld:'vVALUECARD4',pic:'ZZ,ZZZ,ZZ9'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'},{av:'AV16Axes',fld:'vAXES',pic:''},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'gx.fn.getCtrlProperty("NOTIFICATIONSSUBTITLE","Caption")',ctrl:'NOTIFICATIONSSUBTITLE',prop:'Caption'},{av:'AV14AdditionalDataCard1',fld:'vADDITIONALDATACARD1',pic:''},{av:'AV12AdditionalDataCard2',fld:'vADDITIONALDATACARD2',pic:''},{av:'AV10AdditionalDataCard3',fld:'vADDITIONALDATACARD3',pic:''},{av:'AV8AdditionalDataCard4',fld:'vADDITIONALDATACARD4',pic:''}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[{ctrl:'HOMESAMPLEDATA__PRODUCTSTATUS',prop:'Columnclass'}]];
   this.EvtParms["GRIDNOTIFICATIONS.LOAD"] = [[{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'}],[{ctrl:'vNOTIFICATIONICON',prop:'Format'},{av:'AV28NotificationIcon',fld:'vNOTIFICATIONICON',pic:''}]];
   this.EvtParms["GRIDNOTIFICATIONS_FIRSTPAGE"] = [[{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'GRIDNOTIFICATIONS_nEOF'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'}],[]];
   this.EvtParms["GRIDNOTIFICATIONS_PREVPAGE"] = [[{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'GRIDNOTIFICATIONS_nEOF'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'}],[]];
   this.EvtParms["GRIDNOTIFICATIONS_NEXTPAGE"] = [[{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'GRIDNOTIFICATIONS_nEOF'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'}],[]];
   this.EvtParms["GRIDNOTIFICATIONS_LASTPAGE"] = [[{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'GRIDNOTIFICATIONS_nEOF'},{ctrl:'GRIDNOTIFICATIONS',prop:'Rows'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'}],[]];
   this.EvtParms["GRID_FIRSTPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["GRID_PREVPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["GRID_NEXTPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["GRID_LASTPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV29SDTNotificationsData',fld:'vSDTNOTIFICATIONSDATA',grid:105,pic:'',hsh:true},{av:'GRIDNOTIFICATIONS_nFirstRecordOnPage'},{av:'nRC_GXsfl_105',ctrl:'GRIDNOTIFICATIONS',prop:'GridRC'},{av:'AV5HomeSampleData',fld:'vHOMESAMPLEDATA',grid:126,pic:'',hsh:true},{av:'nRC_GXsfl_126',ctrl:'GRID',prop:'GridRC'}],[]];
   this.setVCMap("AV5HomeSampleData", "vHOMESAMPLEDATA", 0, "CollWWPBaseObjects\HomeSampleData.HomeSampleDataItem", 0, 0);
   this.setVCMap("AV29SDTNotificationsData", "vSDTNOTIFICATIONSDATA", 0, "CollWWPBaseObjects\SDTNotificationsData.SDTNotificationsDataItem", 0, 0);
   this.setVCMap("AV29SDTNotificationsData", "vSDTNOTIFICATIONSDATA", 0, "CollWWPBaseObjects\SDTNotificationsData.SDTNotificationsDataItem", 0, 0);
   this.setVCMap("AV29SDTNotificationsData", "vSDTNOTIFICATIONSDATA", 0, "CollWWPBaseObjects\SDTNotificationsData.SDTNotificationsDataItem", 0, 0);
   GridnotificationsContainer.addRefreshingVar({rfrVar:"AV29SDTNotificationsData"});
   GridnotificationsContainer.addRefreshingVar({rfrVar:"AV5HomeSampleData"});
   GridnotificationsContainer.addRefreshingParm({rfrVar:"AV29SDTNotificationsData"});
   GridnotificationsContainer.addRefreshingParm({rfrVar:"AV5HomeSampleData"});
   GridContainer.addRefreshingVar({rfrVar:"AV5HomeSampleData"});
   GridContainer.addRefreshingVar({rfrVar:"AV29SDTNotificationsData"});
   GridContainer.addRefreshingParm({rfrVar:"AV5HomeSampleData"});
   GridContainer.addRefreshingParm({rfrVar:"AV29SDTNotificationsData"});
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationIconClass"], this.GXValidFnc[107], "AV29SDTNotificationsData");
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationTitle"], this.GXValidFnc[108], "AV29SDTNotificationsData");
   this.addGridBCProperty("Sdtnotificationsdata", ["NotificationDatetime"], this.GXValidFnc[109], "AV29SDTNotificationsData");
   this.addGridBCProperty("Homesampledata", ["ProductName"], this.GXValidFnc[127], "AV5HomeSampleData");
   this.addGridBCProperty("Homesampledata", ["ProductPrice"], this.GXValidFnc[128], "AV5HomeSampleData");
   this.addGridBCProperty("Homesampledata", ["ProductStatus"], this.GXValidFnc[129], "AV5HomeSampleData");
   this.Initialize( );
});
gx.wi( function() { gx.createParentObj(wwpbaseobjects.home);});
